package domain.game;

public enum CardType {
    EXPLODING_KITTEN,
    DEFUSE,
    ATTACK,
    SHUFFLE,
    PLACEHOLDER_CARD,
    BEARD_CAT,
    HAIRY_POTATO_CAT,
    TACOCAT,
    RAINBOW_RALPHING_CAT,
    SKIP,
    SEE_THE_FUTURE,
    SUPER_SKIP,
    REVERSE,
    BURY,
    SWAP_TOP_AND_BOTTOM,
    DRAW_FROM_BOTTOM
}
